### ISSUE TITLE
Grade number validation

### ISSUE THREAD

**Issue by alickbass** [toehook/slap-ios#15]
For now, grade's number is just `Int`. That means that we can have the grade like: `129123123A+`. This is definitely bullshit, that is why I think it will make sense to make grade's number as `enum` with back `Int`. Something like:

```swift
enum Number: Int {
    case one = 1, two, thee, four
    case five, six, seven, eight, nine
}
```

and then the Grade will be created as following:

```swift
Grade(.six, .a, plus: true)
```
instead of:

```swift
Grade(12387182364872, .a, plus: true)
```

**Comment by alickbass** [comment]
@davidvanleeuwen what do you think?

**Comment by davidvanleeuwen** [comment]
![yes](https://media.giphy.com/media/WJjLyXCVvro2I/giphy.gif)

**Comment by davidvanleeuwen** [comment]
And we could keep it compatible w/ other grading systems this way.

**Comment by alickbass** [comment]
Well yes, we will need to define the conversion later on. But yes, it will be possible to add it later
